apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resnet-server
  template:
    metadata:
      labels:
        app: resnet-server
    spec:
      containers:
        - name: resnet-server
          image: resnet-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001        # inference API
            - containerPort: 8002        # Prometheus metrics
---
apiVersion: v1
kind: Service
metadata:
  name: resnet-server-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8002"
spec:
  selector:
    app: resnet-server
  ports:
    - name: http           # inference
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: metrics        # Prometheus scrape
      protocol: TCP
      port: 8002
      targetPort: 8002
  type: NodePort
